--SELECT * FROM SYS.SYSCOLUMNS WHERE REFERENCEID = (SELECT REFERENCEID FROM SYS.SYSTABLES WHERE TABLENAME = 'SYSTABLES')

--USE PEDALSHOP;

CREATE TABLE Usuario
(
    UserId INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    Username VARCHAR(200),
    Password VARCHAR(200),
    Email VARCHAR(200),
    Nombre VARCHAR(200),
    Apellido VARCHAR(200)
);

CREATE TABLE Producto
(
    ProductoId INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    Nombre VARCHAR(200),
    Descripcion VARCHAR(300),
    Precio DECIMAL(10, 2),
    RutaImagen VARCHAR(300)
);


CREATE TABLE Compra
(
    CompraId INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    UsuarioId INT NOT NULL,
    Fecha TIMESTAMP,
    FOREIGN KEY (UsuarioId) REFERENCES Usuario
);


CREATE TABLE Compra_Detalle
(
    CompraDetalleId INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CompraId INT NOT NULL,
    ProductoId INT NOT NULL,
    Cantidad INT,
    FOREIGN KEY (CompraId) REFERENCES Compra,
    FOREIGN KEY (ProductoId) REFERENCES Producto
);





